apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: get-ing
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: get.cloudpunk.shop
    http:
      paths:
      - backend:
          service:
            name: get-service
            port:
              number: 80
        path: "/"
        pathType: Prefix